### ISSUE TITLE
404 data.json

### ISSUE THREAD

**Issue by tebraDev** [markgrancapal/filipino_cuisine#3]
Hey

Your [Filipino Cuisine](https://flutter.github.io/samples/web/filipino_cuisine/#/ ) app does not work because there is no [data.json](https://flutter.github.io/data.json) on the websever 

Cheers

**Comment by yogavivoniels** [comment]
Uncaught FormatException: SyntaxError: Unexpected token < in JSON at position 0
    at Object.a (https://flutter.github.io/samples/web/filipino_cuisine/main.dart.js:3856:3)
    at Object.afF (https://flutter.github.io/samples/web/filipino_cuisine/main.dart.js:6298:9)
    at SU.cE (https://flutter.github.io/samples/web/filipino_cuisine/main.dart.js:32379:26)
    at https://flutter.github.io/samples/web/filipino_cuisine/main.dart.js:35486:17
    at a62.a (https://flutter.github.io/samples/web/filipino_cuisine/main.dart.js:5481:72)
    at a62.$2 (https://flutter.github.io/samples/web/filipino_cuisine/main.dart.js:30342:23)
    at a50.$1 (https://flutter.github.io/samples/web/filipino_cuisine/main.dart.js:30334:30)
    at JR.lB (https://flutter.github.io/samples/web/filipino_cuisine/main.dart.js:31120:40)
    at a1L.$0 (https://flutter.github.io/samples/web/filipino_cuisine/main.dart.js:30637:11)
    at Object.pk (https://flutter.github.io/samples/web/filipino_cuisine/main.dart.js:5605:40)

**Comment by Pyrolistical** [comment]
its using the wrong public path.

its loading `https://flutter.github.io/data.json`
the correct urls seems to be `https://flutter.github.io/samples/web/filipino_cuisine/data.json`
